export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS =  "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS =  "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_PROFILE_REQUEST = "PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS =  "PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "PROFILE_FAILURE";
